(package "savefold"
         "0.0.1"
         "persistence for various folding systems")

(website-url "https://github.com/jcfk/savefold.el")
(keywords "convenience")

(package-file "savefold.el")
(files "*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "28.1")
(depends-on "origami")
(development
  (depends-on "buttercup"))
(load-paths "./tests")
